name: Build Library

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  pack:
    name: Test and Pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore Solution
        run: dotnet restore

      - name: Run Unit Tests
        run: dotnet test -c Release --logger "console;verbosity=detailed" Starnet.Tests

      - name: Get Commit Hash
        id: commit
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Get Assembly Information
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: assembly
        with:
          proj-path: Starnet/Starnet.csproj
          
      - name: Pack NuGet Package
        run: dotnet pack -c Release Starnet
        
      - name: Rename NuGet Package
        run: |
          mv \
          ${{ github.workspace }}/Starnet/bin/Release/LBPUnion.Starnet.${{ steps.assembly.outputs.version }}.nupkg \
          ${{ github.workspace }}/Starnet/bin/Release/LBPUnion.Starnet.${{ steps.assembly.outputs.version }}.${{ steps.commit.outputs.hash }}.nupkg
          
      - name: Upload NuGet Package
        uses: actions/upload-artifact@v3.1.1
        with:
          name: LBPUnion.Starnet.${{ steps.assembly.outputs.version }}.${{ steps.commit.outputs.hash }}.nupkg
          path: "${{ github.workspace }}/Starnet/bin/Release/LBPUnion.Starnet.${{ steps.assembly.outputs.version }}.${{ steps.commit.outputs.hash }}.nupkg"
          if-no-files-found: error
          retention-days: 3