#file: noinspection SpellCheckingInspection
name: Automatic Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build NuGet Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Get Version Information
        id: version
        run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Restore Solution
        run: dotnet restore

      - name: Build NuGet Package
        run: dotnet pack -c Release /p:Version=${{ steps.version.outputs.version }} Starnet

      - name: Upload Package Artifact
        uses: actions/upload-artifact@master
        with:
          name: LBPUnion.Starnet.${{ steps.version.outputs.version }}.nupkg
          path: ${{ github.workspace }}/Starnet/bin/Release/LBPUnion.Starnet.${{ steps.version.outputs.version }}.nupkg
          if-no-files-found: error
          retention-days: 3

  github:
    name: Release Package to GitHub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Get Version Information
        id: version
        run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Download Package Artifact
        uses: actions/download-artifact@master
        with:
          name: LBPUnion.Starnet.${{ steps.version.outputs.version }}.nupkg
          path: ${{ github.workspace }}/artifacts

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: true
          files: |
            ${{ github.workspace }}/artifacts/LBPUnion.Starnet.${{ steps.version.outputs.version }}.nupkg

  nuget:
      name: Release Package to NuGet
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x

        - name: Get Version Information
          id: version
          run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

        - name: Download Package Artifact
          uses: actions/download-artifact@master
          with:
            name: LBPUnion.Starnet.${{ steps.version.outputs.version }}.nupkg
            path: ${{ github.workspace }}/artifacts

        - name: Create NuGet Release
          run: | 
            dotnet nuget push \
            ${{ github.workspace }}/artifacts/LBPUnion.Starnet.${{ steps.version.outputs.version }}.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ secrets.NUGET_TOKEN }}