#file: noinspection SpellCheckingInspection
name: Automatic Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  github:
    name: Release Package to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore Solution
        run: dotnet restore

      - name: Get Version Information
        id: version
        run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Build NuGet Package
        run: dotnet pack -c Release /p:Version=${{ steps.version.output.version }} Starnet

      - name: Create GitHub Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: true
          files: |
            ${{ github.workspace }}/Starnet/bin/Release/LBPUnion.Starnet.${{ steps.version.output.version }}.nupkg
  nuget:
      name: Release Package to NuGet
      runs-on: ubuntu-latest
      steps:
        - name: Checkout from GitHub
          uses: actions/checkout@v3

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x

        - name: Restore Solution
          run: dotnet restore

        - name: Get Version Information
          id: version
          run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

        - name: Build NuGet Package
          run: dotnet pack -c Release /p:Version=${{ steps.version.output.version }} Starnet
          
        - name: Create NuGet Release
          run: | 
            dotnet nuget push \
            ${{ github.workspace }}/Starnet/bin/Release/LBPUnion.Starnet.${{ steps.version.output.version }}.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ secrets.NUGET_TOKEN }}